### ISSUE TITLE
Not knitting empty-spaces.Rmd

### ISSUE THREAD

**Issue by jmarsicek** [EarthCubeGeochron/IRDDive#8]
When trying to knit the current version of empty-spaces.Rmd, I get the following error:

Quitting from lines 48-70 (empty-spaces.Rmd) 
Error in eval(expr, envir, enclos) : object 'nlp' not found
Calls: <Anonymous> ... .f -> withVisible -> eval -> eval -> %>% -> eval -> eval
In addition: There were 43 warnings (use warnings() to see them)
Execution halted

@SimonGoring, the knit was working on your end, but I have no idea why it cannot find 'nlp'.

**Comment by SimonGoring** [comment]
@jmarsicek can you try pulling and then clearing your environment with `rm(list = ls())` and then running the first code block line by line from the R console?  Also pull again, I wonder if it's an issue with the sourced files at line 57.

**Comment by jmarsicek** [comment]
This seems to have worked. Thanks @SimonGoring .
